import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import photo from '../public/JELAY.jpg';

import { motion, transform } from 'framer-motion';

export default function Home() {
  const [toggle, setToggle] = useState(true);
  const [toggleImages, setToggleImages] = useState(false);

  return (
    <div>
      <Head>
        <title>HAPPY BIRTHDAY💛</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.wrapper}>
        <div className={styles.container}>
          {toggle ? (
            <>
              <motion.h1
                initial={{ opacity: 0, y: '-100vw' }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className={styles.title}
              >
                Click me!
              </motion.h1>
              <motion.div
                className={styles.arrow}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 1 }}
              >
                ⬇
              </motion.div>
            </>
          ) : (
            <>
              <motion.button
                initial={{ opacity: 0, scale: 0 }}
                animate={{ opacity: 1, scale: 1 }}
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                className={styles.btn}
                onClick={() => {
                  setToggle(true);
                  setToggleImages(false);
                }}
              >
                Reset
              </motion.button>
            </>
          )}
          <div>
            {toggle ? (
              <motion.div
                initial={{ opacity: 0, scale: 0 }}
                animate={{ opacity: 1, scale: 1 }}
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
              >
                {' '}
                <Image
                  className={styles.giftbox}
                  src='https://cdnjs.cloudflare.com/ajax/libs/flat-ui/2.3.0/img/icons/svg/gift-box.svg'
                  alt='giftbox'
                  object-fit='cover'
                  width={64}
                  height={64}
                  onClick={() => {
                    setToggle(!toggle);
                    setToggleImages(true);
                  }}
                />
              </motion.div>
            ) : (
              <>
                <div className={styles.greetingWrapper}>
                  <motion.h1
                    initial={{ opacity: 0, x: '-100vw' }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 1 }}
                    className={styles.greetingTitle}
                  >
                    HAPPY BIRTHDAY JESSIE! 💛
                  </motion.h1>
                  <motion.p
                    initial={{ opacity: 0, x: '-100vw' }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 1.2 }}
                  >
                    <p>
                      Today is the anniversary of the publication of Robert
                      Frost’s iconic poem “Stopping by Woods on a Snowy
                      Evening,” a fact that spurred the Literary Hub office into
                      a long conversation about their favorite poems, the most
                      iconic poems written in English, and which poems we should
                      all have already read (or at least be reading next). Turns
                      out, despite frequent (false) claims that poetry is dead
                      and/or irrelevant and/or boring, there are plenty of poems
                      that have sunk deep into our collective consciousness as
                      cultural icons. (What makes a poem iconic? For our
                      purposes here, it’s primarily a matter of cultural
                      ubiquity, though unimpeachable excellence helps any case.)
                      So for those of you who were not present for our epic
                      office argument, I have listed some of them here. NB that
                      I limited myself to one poem per poet—which means that the
                      impetus for this list actually gets bumped for the widely
                      quoted (and misunderstood) “The Road Not Taken,” but so it
                      goes. I also excluded book-length poems, because they’re
                      really a different form. Finally, despite the headline,
                      I’m sure there are many, many iconic poems out there that
                      I’ve missed—so feel free to extend this list in the HAPPY BIRTHDAY SAYO JESSIE MAHAL NA MAHAL KITA
                    </p>

                    <p> - VINCENT</p>
                  </motion.p>
                  <motion.p
                    initial={{ opacity: 0, x: '-100vw' }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 1.5 }}
                  ></motion.p>
                </div>
              </>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
